spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/fastsns"
    username: root
    password: fastcampus
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  jmx:
    enabled: false